namespace: madhoshyagnik
name: microservices_kubernetes
version: 0.0.1

readme: readme.md

authors:
  - Madhosh Yagnik

description: Ansible roles for deploying K3s and MetalLB.

license:
  - MIT

tags:
  - kubernetes
  - k3s
  - metallb
  - infrastructure

repository: https://github.com/madhoshyagnik/microservices-kubernetes
