# Inventory for K3s nodes. Shared variables are stored in group_vars/all.yml.
all:
  children:
    control_nodes:
      hosts:
        debian1:
          ansible_host: 192.168.56.11

    worker_nodes:
      hosts:
        debian2:
          ansible_host: 192.168.56.12
        debian3:
          ansible_host: 192.168.56.13
        debian4:
          ansible_host: 192.168.56.14
        debian5:
          ansible_host: 192.168.56.15

    k3s:
      children:
        control_nodes:
        worker_nodes: