# Sets IP range for MetalLB Load Balancer to use

- name: Generate MetalLB configuration
  ansible.builtin.template:
    src: metallb-config.yaml.j2
    dest: /tmp/metallb-config.yaml

- name: Apply MetalLB configuration
  ansible.builtin.command: kubectl apply -f /tmp/metallb-config.yaml

- name: Verify IPAddressPool
  ansible.builtin.command: kubectl get ipaddresspool -n metallb-system
  changed_when: false

- name: Verify L2Advertisement
  ansible.builtin.command: kubectl get l2advertisement -n metallb-system
  changed_when: false