---
# tasks file for k3s

- name: Run bootstrap tasks
  ansible.builtin.include_tasks: bootstrap.yml

- name: Run server tasks
  ansible.builtin.include_tasks: server.yml
  when: inventory_hostname in groups['control_nodes'] | default([])

- name: Run agent tasks
  ansible.builtin.include_tasks: agent.yml
  when: inventory_hostname in groups['worker_nodes'] | default([])

- name: Run configure tasks
  ansible.builtin.include_tasks: configure.yml
  when: inventory_hostname in groups['control_nodes'] | default([])
