---
# tasks file for k3s

- name: Run bootstrap tasks
  ansible.builtin.include_tasks: bootstrap.yml
  when: k3s_action | default('all') in ['all', 'bootstrap']

- name: Run server tasks
  ansible.builtin.include_tasks: server.yml
  when:
    - k3s_action | default('all') in ['all', 'server']
    - inventory_hostname in groups['control'] | default([])

- name: Run agent tasks
  ansible.builtin.include_tasks: agent.yml
  when:
    - k3s_action | default('all') in ['all', 'agent']
    - inventory_hostname in groups['workers'] | default([])

- name: Run configure tasks
  ansible.builtin.include_tasks: configure.yml
  when:
    - k3s_action | default('all') in ['all', 'configure']
    - inventory_hostname in groups['control'] | default([])

- name: Run uninstall tasks
  ansible.builtin.include_tasks: uninstall.yml
  when: k3s_action | default('all') == 'uninstall'

