---
- name: Bootstrap K3s Cluster
  hosts: k3s
  become: true
  gather_facts: true
  roles:
    - role: ./roles/k3s
      vars:
        k3s_action: bootstrap

- name: Install K3s Server
  hosts: control
  become: true
  gather_facts: true
  roles:
    - role: ./roles/k3s
      vars:
        k3s_action: server

- name: Install K3s Workers
  hosts: workers
  become: true
  gather_facts: true
  roles:
    - role: ./roles/k3s
      vars:
        k3s_action: agent

- name: Configure Cluster
  hosts: control
  become: true
  gather_facts: true
  roles:
    - role: ./roles/k3s
      vars:
        k3s_action: configure