---
- name: Deploy K3s Cluster
  hosts: k3s
  become: true
  gather_facts: true
  roles:
    - role: ../roles/k3s

- name: Install Cluster Addons
  hosts: localhost
  connection: local
  gather_facts: false
  roles:
    - role: ../roles/metallb
    - role: ../roles/rancher
    - role: ../roles/kubevirt
    - role: ../roles/opentelemetry