---
- name: Revert K3s Installation
  hosts: k3s
  become: true
  gather_facts: true
  tasks:
    - name: Run uninstall tasks
      ansible.builtin.include_role:
        name: ../roles/k3s
        tasks_from: uninstall.yml
